INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Get the process ID that contain name','ps -eaf | grep ${text:Process_Name} | grep -v');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Find files in a folder','find ${text:Path} -name " ${text:Name}"');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Kill a process by PID','kill ${text:PID}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Kill all processes by Name','kill ${text:Name}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Start a HTTP file server on this folder with port','python -m "SimpleHTTPServer" ${text:Port}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','List Contents of Folder','ls -lrt ${text:Path}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','SCP a file from one server to another','scp ${text:Source_UserID}@${text:Source_Machine_Name}:/${text:Source_Full_Path} ${text:Destination_Full_Path}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Get last N lines from log','tail -${text:Number_Of_Lines} ${text:File_Name}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('EmailTemplate','RequestCompleted','conf/response.txt');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('EmailTemplate','RequestReceived','conf/request.txt');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Start a HTTP file server on this folder with port','python -m "HTTPServer" ${text:Port}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Start Tomcat','${text:Path_of_Tomcat}/start.sh');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Run the google sheets job','${text:Path_of_Googlesheets_JAR} start.sh');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Archive the logs and delete older than','zip ${text:Path_of_logs_folder}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Get lines in log which has a specific word','tail -${text:Number_Of_Lines} ${text:File_Name} | grep ${text:Match_String}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Remove or delete a file (force)','rm -f ${text:Path}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Remove or delete a folder (force)','rm -rf ${text:Path}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','Stop tomcat','${text:Path_of_Tomcat}/shutdown.sh');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('Action','List files in HDFS','hadoop fs -ls ${text:Path}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('TeamNameMapping','Team1','youremail@yourcompany.com');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('EmailTemplateSubject','RequestCompleted','AutoOps: Request accepted: ${txnNumber}');
INSERT INTO OAT_MAPPING (category,column_name,mapped_value) VALUES ('EmailTemplateSubject','RequestReceived','AutoOps: Operation Requested: ${txnNumber}');